### ISSUE TITLE
change label of hereditary fructose intolerance to Fructosemia – HFI

### ISSUE THREAD

**Issue by nicolevasilevsky** [Orphanet/ORDO#14]
A MONDOO user requested that we change the label of MONDO_0009249 hereditary fructose intolerance to Fructosemia – HFI

I wanted to check with you all before proceeding. Could you please comment?

See https://github.com/monarch-initiative/mondo/issues/240

**Comment by nicolevasilevsky** [comment]
cc @Orphanet

**Comment by annieolry** [comment]
Hi,
Fructosemia is a clinical sign rather than the disease itself. Fructosemia can be observed in other disorders, Orphanet will keep hereditary fructose intolerance as prefered term (that is largely used in the medical litterature). Note: Hereditary fructosemia is already a synonym of hereditary fructose intolerance.

**Comment by nicolevasilevsky** [comment]
Thanks Annie! I'll close this ticket.
